import type { Metadata } from "next";
import { Inter, Overpass } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import Header from "./_components/Header";

const overpass = Overpass({
  variable: "--font-overpass",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  weight: "800",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Check It - Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${overpass.variable} ${inter.variable} antialiased`}>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
